### ISSUE TITLE
armhf build not working on pi4?

### ISSUE THREAD

**Issue by NEITG** [Nico640/docker-unms#10]
Hi, I just had to redeploy your UNMS package into Docker on Pi4. Had it working okay a few weeks back but trying to run my same Docker deployment script using the armhf tag I'm now getting an unsupported platform error. 

Any known issues for this in the current build?

Thanks

**Comment by Nico640** [comment]
Hi,
I have no problems running the image on a Pi4 with the armhf tag.
I am using the command specified in the readme (docker run), what are you using to deploy the image?
The only thing that changed architecture wise is that with the move from Travis CI to GitLab CI, the armhf image shows up as amd64 on the docker hub, even though it is build for and from arm. I haven't looked into that yet as I didn't have any problems.

**Comment by NEITG** [comment]
Sure, it's below. This is the same command that worked a month or so back.

Many thanks


docker service create \
  --name=unms \
  --publish=8080:80/tcp \
  --publish=8443:443/tcp \
  --publish 2055:2055/udp \
  --env TZ=Europe/London \
  --constraint=node.id==manager \
  --mount=type=bind,src=/home/pi/unms,dst=/config \
  nico640/docker-unms:armhf

**Comment by NEITG** [comment]
Thats a typo on the constraint where I was trying to get it working but with or without it fails

**Comment by Nico640** [comment]
Hi,
The problem is indeed the architecture that is displayed incorrectly on the docker hub.
I'm gonna look into getting that fixed. In the meantime, you can use the --no-resolve-image parameter on the docker service create command to stop docker from checking whether the architecture is correct.

**Comment by NEITG** [comment]
Great, thanks I shall give that a try

**Comment by zimmertr** [comment]
The following `docker-compose.yml` file fails on my Odroid XU4Q. Which is an `ARMv7` device. Any idea why?

```
version: '3'
services:
    unms:
        image: nico640/docker-unms:armhf
        restart: unless-stopped
        container_name: unms
        ports:
            - 81:80
            - 444:443
            - 2055:2055/udp
        volumes:
            - /root/docker/unms/:/config
        environment:
            - TZ=America/Los_Angeles
            - PUBLIC_HTTPS_PORT=444
            - PUBLIC_WS_PORT=443
```

Here is the error message on startup: 
```
$> docker-compose up -d
Creating unms ... error

ERROR: for unms  Cannot start service unms: no status provided on response: unknown

ERROR: for unms  Cannot start service unms: no status provided on response: unknown
ERROR: Encountered errors while bringing up the project.
```
