### ISSUE TITLE
Open Ports for Postgresql

### ISSUE THREAD

**Issue by jcsandoval98** [Nico640/docker-unms#100]
Im trying to get into the database, im forwarding 5432 tcp but i still seems closed

this is my compose stack
```
version: '2'
services:
  unms:
    image: nico640/docker-unms:latest
    restart: always
    environment:
      - TZ=America/Cancun
      - PUBLIC_WS_PORT=9984
      - PUBLIC_HTTPS_PORT=9985
      
    ports:
       - 9984:80
       - 9985:443
       - 9986:5432
    volumes:
      - unms:/config

volumes:
    unms: 
```
