### ISSUE TITLE
Location lost after recreating container

### ISSUE THREAD

**Issue by iNenadnano** [Nico640/docker-unms#113]
Hello,

First of all, let me thank you for this docker image.

I am running it using docker compose which looks as follows:
```
services:
  unms:
    image: nico640/docker-unms:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 2055:2055/udp
    environment:
      - TZ=Europe/Belgrade
      - SSL_CERT=unms.crt
      - SSL_CERT_KEY=unms.key
    volumes:
      - ./config:/config
```
The issue I have encountered is that device location gets lost when container is recreated. For example, I was initially running the container without the custom certificates During that time, I have set location for several devices using the UISP API (`PUT` method on `/devices/{deviceId}/location` endpoint}. However, after recreating the container with environment variables for custom certificate added, the location was lost. Is this the expected behaviour or am I doing something wrong?

Thank you.
