### ISSUE TITLE
problem with airmax M devices when using the container behind nginx

### ISSUE THREAD

**Issue by aris-2** [Nico640/docker-unms#116]
Hello, due to the new uisp payment plans I am migrating several instances to a local server, the idea is that each one has its own subdomain. 

I manage to configure nginx successfully so I have access to my uisp instances from each subdomain without problems, I also manage to adopt airmax ac devices successfully, the problem arises when I try to adopt airmax M devices such as nanostation M5, a timed out waiting error occurs ssl on airmax M devices 

I tried exposing a single container by generating the certificate from the uisp configurations and managed to adopt the airmax M devices successfully 

so my problem seems to be in the nginx configuration but I can't find the error

I share my configurations, I guess there will be several of us who are going to struggle with these problems due to the new uisp payment plans

```

 nginx:
    image: jonasal/nginx-certbot
    container_name: nginx
    volumes:
      - ./nginx_secrets:/etc/letsencrypt
      - ./nginx_conf.d:/etc/nginx/user_conf.d
    environment:
      - CERTBOT_EMAIL=xxxx@xxxx.com.
    ports:
      - "80:80"
      - "443:443"

  unms-david:
    image: nico640/docker-unms:latest
    container_name: unms
    restart: always
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./unms:/config
    ports:
      - 172.25.0.1:8003:443
    networks:
      unms_network:
        ipv4_address: 172.26.0.2 
```

```

ssl_certificate         /etc/letsencrypt/live/test-name/fullchain.pem;
ssl_certificate_key     /etc/letsencrypt/live/test-name/privkey.pem;
ssl_trusted_certificate /etc/letsencrypt/live/test-name/chain.pem;
ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name uisp.xxxxx.com;

    location / {
        proxy_pass https://172.26.0.1:8003;
        proxy_set_header Host $host;    
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
        proxy_set_header X-Forwarded-Proto $scheme;  
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        client_max_body_size 100M;
    }
}
```
