### ISSUE TITLE
Backup restore, http error 413 due to reverse proxy

### ISSUE THREAD

**Issue by brontide** [Nico640/docker-unms#45]
I'm opening this and will close it momentarily, this is for documentation only.

When bringing up this container on k8s I ended up being unable to restore, it would error out with http 413.  I confirmed that the docker image/unms itself was not the problem it was related to the ingress-nginx service.  Below is an example of an ingress resource that has the appropriate annotations.

The key is **nginx.ingress.kubernetes.io/proxy-body-size: "0"** which set an unlimited body size for this application.  For other reverse proxy systems it might be a slightly different annotation.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: unms-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - unms.mydomain.com
    secretName: le-unms
  rules:
  - host: unms.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: unms-service
          servicePort: https
```

This is running on a rPi cluster using longhorn for distributed storage.  It's not as fast as my intel server but it's fast enough.  Initial startup was a solid 10 minutes, same for restoring the backup, but once running it's great.

```
$ kubectl top pods -l app=unms
NAME     CPU(cores)   MEMORY(bytes)   
unms-0   298m         888Mi
```
