### ISSUE TITLE
ucrm can't contact with unms

### ISSUE THREAD

**Issue by lacrimal** [Nico640/docker-unms#66]
Hi,
Docker-unms in infinite loop waiting for response from 127.0.0.1:8081. This is qnap device. Worked just fine and died few weeks ago. I know that this problem is probably specific to qnap and probably firmware update. No matter when I start it from GUI or console with docker-compose. Checked from 1.310 version to latest - same symptoms.
Can you suggest what I can suggest to support ?

```
{"message":"Synchronizing with UNMS.","channel":"web.sh","datetime":"2022-04-02T16:47:30+02:00","severity":"INFO","level":200}
...
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2022-04-02T16:48:41+02:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2022-04-02T16:48:45+02:00","severity":"INFO","level":200}
{"message":"UNMS did not start in time, restarting container.","channel":"web.sh","datetime":"2022-04-02T16:48:45+02:00","severity":"WARNING","level":300}
make: *** [Makefile:22: server_with_migrate] Error 1
/usr/src/ucrm/scripts/init_log.sh
```

**Comment by Nico640** [comment]
Did you try fresh installing the container by using a different /config mapping or clearing the existing data (but of course backing up the data before doing so)? Also, please paste a bigger portion of the logs outputted by the `docker logs container_name` command or the unms.log file. There probably is an repeating pattern and an error in there somewhere.

**Comment by lacrimal** [comment]
Hi,
Tried several things:
- fresh container installation
- other versions (>= 1.3.10)
- changes in dockerfile

My docker file that worked just fine previously (it was 1.3.10) :

```
version: '3.3'
services:
  unms:
    image: nico640/docker-unms:latest
    restart: always
    ports:
      - 8888:80
      - 8889:443
      - 2055:2055/udp
    environment:
      - TZ=Europe/Warsaw
      - SSL_CERT=cert
      - SSL_CERT_KEY=key
    volumes:
      - /share/Container/unms_data:/config
```
Attached logs, thanks you for your time and help.
[ucrm.log](https://github.com/Nico640/docker-unms/files/8415579/ucrm.log)
[unms.log](https://github.com/Nico640/docker-unms/files/8415580/unms.log)
